#!/usr/bin/env bash
# Create a new review package from Review_Template.md with the next sequential ID.
#
# Usage:
#   ./scripts/new_review_package.sh <Category> <topic_slug> [options]
#
# Examples:
#   ./scripts/new_review_package.sh Screens level_select_shell
#   ./scripts/new_review_package.sh Design_System token_refresh --task-name "Token Refresh"
#   ./scripts/new_review_package.sh Architecture folder_structure --phase "Phase 3" --update-index
#
# Categories: Design_System | Screens | Gameplay | Architecture | Economy | Releases
#   (also accepts design-system, screens, etc.)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REVIEWS_DIR="$REPO_ROOT/docs/99_Reviews"
TEMPLATE="$REVIEWS_DIR/Review_Template.md"
README="$REVIEWS_DIR/README.md"

TASK_NAME=""
PHASE=""
OWNER="Cursor"
UPDATE_INDEX=false
DRY_RUN=false

usage() {
  sed -n '2,14p' "$0"
  exit "${1:-0}"
}

normalize_category() {
  local raw="${1//-/_}"
  raw="$(echo "$raw" | tr '[:upper:]' '[:lower:]')"
  case "$raw" in
    design_system) echo "Design_System" ;;
    screens) echo "Screens" ;;
    gameplay) echo "Gameplay" ;;
    architecture) echo "Architecture" ;;
    economy) echo "Economy" ;;
    releases) echo "Releases" ;;
    *)
      echo "ERROR: Unknown category '$1'. Use: Design_System, Screens, Gameplay, Architecture, Economy, Releases" >&2
      exit 1
      ;;
  esac
}

review_type_for_category() {
  case "$1" in
    Design_System) echo "Design System" ;;
    Screens) echo "Screen" ;;
    Gameplay) echo "Gameplay" ;;
    Architecture) echo "Architecture" ;;
    Economy) echo "Economy" ;;
    Releases) echo "Release" ;;
  esac
}

slug_to_title() {
  python3 -c "print(' '.join(w.capitalize() for w in '''$1'''.split('_')))"
}

next_review_id() {
  local max=0
  local f base id
  shopt -s nullglob
  for f in "$REVIEWS_DIR"/*/*.md; do
    base="$(basename "$f")"
    if [[ "$base" =~ ^([0-9]{4})_ ]]; then
      id="${BASH_REMATCH[1]}"
      if (( 10#$id > max )); then
        max=$((10#$id))
      fi
    fi
  done
  printf "%04d" $((max + 1))
}

if [[ $# -lt 2 ]]; then
  usage 1
fi

CATEGORY="$(normalize_category "$1")"
TOPIC_SLUG="$2"
shift 2

while [[ $# -gt 0 ]]; do
  case "$1" in
    --task-name)
      TASK_NAME="${2:-}"
      shift 2
      ;;
    --phase)
      PHASE="${2:-}"
      shift 2
      ;;
    --owner)
      OWNER="${2:-}"
      shift 2
      ;;
    --update-index)
      UPDATE_INDEX=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    -h|--help)
      usage 0
      ;;
    *)
      echo "ERROR: Unknown option '$1'" >&2
      usage 1
      ;;
  esac
done

if [[ ! -f "$TEMPLATE" ]]; then
  echo "ERROR: Template not found: $TEMPLATE" >&2
  exit 1
fi

if [[ ! "$TOPIC_SLUG" =~ ^[a-z][a-z0-9_]*$ ]]; then
  echo "ERROR: topic_slug must be lowercase snake_case (e.g. level_select_shell)" >&2
  exit 1
fi

if [[ -z "$TASK_NAME" ]]; then
  TASK_NAME="$(slug_to_title "$TOPIC_SLUG")"
fi

NEXT_ID="$(next_review_id)"
DATE="$(date +%Y-%m-%d)"
REVIEW_TYPE="$(review_type_for_category "$CATEGORY")"
FILENAME="${NEXT_ID}_${TOPIC_SLUG}.md"
TARGET_DIR="$REVIEWS_DIR/$CATEGORY"
TARGET_FILE="$TARGET_DIR/$FILENAME"
REL_PATH="docs/99_Reviews/$CATEGORY/$FILENAME"

if [[ -f "$TARGET_FILE" ]]; then
  echo "ERROR: File already exists: $TARGET_FILE" >&2
  exit 1
fi

if [[ "$DRY_RUN" == true ]]; then
  echo "Would create: $TARGET_FILE"
  echo "Review ID: $NEXT_ID"
  echo "Task name: $TASK_NAME"
  exit 0
fi

mkdir -p "$TARGET_DIR"

python3 - "$TEMPLATE" "$TARGET_FILE" "$TASK_NAME" "$NEXT_ID" "$DATE" "${PHASE:-TBD}" "$OWNER" "$REVIEW_TYPE" "$REL_PATH" <<'PY'
import sys
from pathlib import Path

template_path, target_path, task_name, review_id, date, phase, owner, review_type, rel_path = sys.argv[1:]

text = Path(template_path).read_text(encoding="utf-8")
replacements = [
    ("# Review Package: [Task Name]", f"# Review Package: {task_name}"),
    ("| **Review ID** | NNNN |", f"| **Review ID** | {review_id} |"),
    ("| **Date** | YYYY-MM-DD |", f"| **Date** | {date} |"),
    ("| **Phase** | e.g. Phase 2 — Design System |", f"| **Phase** | {phase} |"),
    ("| **Owner** | Cursor / Human name |", f"| **Owner** | {owner} |"),
    (
        "| **Status** | Draft / Ready for Review / Approved / Changes Requested |",
        "| **Status** | Draft |",
    ),
    (
        "| **Review Type** | Design System / Screen / Gameplay / Architecture / Economy / Release |",
        f"| **Review Type** | {review_type} |",
    ),
    ("| **Template Version** | v2 |", "| **Template Version** | v2 |"),
    (
        "> Scaffold with `scripts/new_review_package.sh` — do not copy this file manually unless the script is unavailable.",
        "> Generated by `scripts/new_review_package.sh` (template v2).",
    ),
    (
        "> Template version: **v2**",
        f"> File: `{rel_path}`",
    ),
]
for old, new in replacements:
    text = text.replace(old, new)

Path(target_path).write_text(text, encoding="utf-8")
PY

if [[ "$UPDATE_INDEX" == true ]]; then
  python3 - "$README" "$NEXT_ID" "$CATEGORY" "$FILENAME" <<'PY'
import re
import sys
from pathlib import Path

readme_path = Path(sys.argv[1])
review_id = sys.argv[2]
category = sys.argv[3]
filename = sys.argv[4]
next_id = f"{int(review_id) + 1:04d}"

text = readme_path.read_text(encoding="utf-8")
row = f"| {review_id} | [{category}/{filename}]({category}/{filename}) | Draft |"

if row in text:
    print(f"Index already contains {review_id}; skipping README update.")
    sys.exit(0)

pattern = re.compile(
    r"(\| \d{4} \| \[[^\]]+\]\([^\)]+\) \| [^\|]+ \|\n)\n\*\*Next ID:\*\* \d{4}",
    re.MULTILINE,
)
match = pattern.search(text)
if not match:
    raise SystemExit("Could not find review index table footer in README.md")

text = pattern.sub(rf"\1{row}\n\n**Next ID:** {next_id}", text, count=1)
readme_path.write_text(text, encoding="utf-8")
print(f"Updated {readme_path}")
PY
fi

echo "Created review package:"
echo "  $TARGET_FILE"
echo ""
echo "Next steps:"
echo "  1. Fill in Task Summary, Motivation, Risk, Dependencies, Product Impact, and file lists"
echo "  2. Complete Future Technical Debt and Recommended Next Task sections"
echo "  3. Add screenshots if UI changed; run tests/analyze"
echo "  4. Mark Ready For when complete"
if [[ "$UPDATE_INDEX" != true ]]; then
  echo "  4. Add a row to docs/99_Reviews/README.md (or re-run with --update-index)"
fi
